apps/apis/urls.py
from django.urls import path, include
from rest_framework.authtoken import views
from rest_framework_swagger.views import get_swagger_view

from apps.apis.views import *

app_name = 'apis'

urlpatterns = [

    path('register/', CreateUser.as_view(), name='register'),
    path('login/', views.ObtainAuthToken.as_view(), name='login'),
    path('weather/<str:city>/', Weather.as_view(), name='weather'),

]

apps/weather_ui/urls.py
from django.urls import path

from apps.weather_ui.views import *

app_name = 'weather'

urlpatterns = [

    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('', Weather.as_view(), name='weather-ui'),

]

weather/urls.py
from django.conf.urls.static import static

from django.contrib import admin

from django.urls import path, include

from rest_framework_swagger.views import get_swagger_view


from weather import settings
from weather import views
from weather.views import dash
api_urls = [path('apis/', include('apps.apis.urls', namespace='apis')), ]
urlpatterns = [
                  path('weather/', include('apps.weather_ui.urls')),
                  path('', dash.as_view()),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schema_view = get_swagger_view(patterns=api_urls, title='apis')

urlpatterns = urlpatterns + api_urls + [path('docs/', schema_view), ]

apps/apis/models.py
from django.db import models

class User(models.Model):
    nickname = models.CharField(verbose_name='50' , max_length=50)
    password = models.CharField(verbose_name='50', max_length=50)

    class Meta: 
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.nickname

apps/weather_ui/models.py
from django.db import models

class User(models.Model):
    nickname = models.CharField(verbose_name='50' , max_length=50)
    password = models.CharField(verbose_name='50', max_length=50)

    class Meta: 
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.nickname

apps/apis/views.py
import requests
from django.contrib.auth import get_user_model
from rest_framework import permissions, status
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import BasePermission
from rest_framework.response import Response
from rest_framework.views import APIView
from apps.apis.serializers.user_serializer import UserSerializer
from apps.core.auth_user import IsUser
from apps.core.get_weather_data import GetWeatherData

from weather.settings import WEATHER_API_BASE_URL, WEATHER_API_ACCESS_KEY


class CreateUser(CreateAPIView):
    
    model = get_user_model()
    permission_classes = [
        permissions.AllowAny
    ]
    serializer_class = UserSerializer


class Weather(IsUser, APIView):

    def get(self, request, **kwargs):
        city = kwargs['city']

        response = GetWeatherData(city)
        status_value = status.HTTP_200_OK

        if response is None:
            status_value = status.HTTP_204_NO_CONTENT

        return Response(response, status=status_value)

apps/weather_ui/views.py
from django.contrib.auth import get_user_model, authenticate, logout, login
from django.shortcuts import redirect
from rest_framework import permissions
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from apps.core.auth_user import IsUser
from apps.core.get_weather_data import GetWeatherData
from apps.weather_ui.serializers.user_ui_serializer import UserUiRegisterSerializer, UserUiLoginSerializer


class Register(APIView):
    exclude_from_schema = True
    permission_classes = [
        permissions.AllowAny
    ]

    renderer_classes = [TemplateHTMLRenderer]
    serializer_class = UserUiRegisterSerializer
    template_name = 'auth_or_register.html'

    def get(self, request):
        return Response({'form': self.serializer_class, 'type': 'register'})

    def post(self, request):
        form = self.serializer_class(data=request.data)
        if not form.is_valid():
            return Response({'form': form, 'type': 'register'})
        form.save()
        return redirect('weather:login')


class Login(APIView):
    exclude_from_schema = True
    permission_classes = [
        permissions.AllowAny
    ]
    model = get_user_model()
    renderer_classes = [TemplateHTMLRenderer]
    serializer_class = UserUiLoginSerializer
    template_name = 'auth_or_register.html'

    def get(self, request):
        return Response({'form': self.serializer_class, 'type': 'login'})

    def post(self, request):
        form = self.serializer_class(data=request.data)
        if form.is_valid():
            user = authenticate(username=form.validated_data['username'], password=form.validated_data['password'])
            if user is None:
                logout(request)
                return Response({'form': form, 'type': 'login', 'error': True})
            else:
                login(request, user)


        else:
            return Response({'form': form, 'type': 'login'})

        return redirect('weather:weather-ui')


class Logout(IsUser, APIView):
    exclude_from_schema = True

    def get(self, request):
        logout(request)

        return redirect('weather:login')


class Weather(IsUser, APIView):
    template_name = 'weather.html'
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):
        return Response({'type': 'weather-get'})

    def post(self, request, **kwargs):
        city = request.data['city']

        response = GetWeatherData(city)

        return Response(response)

weather/views.py
from django.shortcuts import redirect, render
from django.views import View

class dash(View):

    def get(self, request, *args, **kwargs):
        return redirect('weather:login')

templates/auth_or_register.html
{% extends 'base.html' %}
{% load rest_framework %}


{% block content %}


    <!-- main -->
    <div class="main-w3layouts wrapper">
        {% if type == 'register' %}
            <h1>Регистрация</h1>
        {% elif type == 'login' %}
            <h1>Авторизация</h1>
        {% endif %}
        <div class="main-agileinfo">
            <div class="agileits-top">
                <form action="{% if type == 'register' %}{% url 'weather:register' %}{% elif type == 'login' %}
{% url 'weather:login' %}{% endif %}"
                      method="post">

                    {% csrf_token %}
                    {% render_form form %}
                    <div class="wthree-text">

                        <div class="clear"></div>
                    </div>
                    {% if type == 'register' %}
                        <input type="submit" value="Зарегестрироваться.">
                    {% elif type == 'login' %}
                        <input type="submit" value="Авторизироваться">
                    {% endif %}

                </form>
                {% if type == 'register' %}
                    <p><a href="{% url 'weather:login' %}"> Авторизоваться</a></p>
                {% elif type == 'login' %}
                    <p>Нету аккаунта? <a href="{% url 'weather:register' %}"> Зарегестрируйтесь.</a></p>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% if user.is_authenticated %}
        Уже авторизован
        <script type="text/javascript">

            window.location.replace('{% url 'weather:weather-ui' %}');
        </script>
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="{% static 'user/style.css' %}">
    <meta charset="UTF-8">
    <title>{{ type }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- //web font -->
    {% block styles %}
    {% endblock %}
</head>
<body>
<!-- main -->
{% block content %}

{% endblock %}
<!-- //main -->
</body>

{% block scripts %}
    {% if user.is_authenticated %}
        Уже авторизован
        <script type="text/javascript">

            window.location.replace('{% url 'weather:weather-ui' %}');
        </script>
    {% endif %}
{% endblock %}
</html>

templates/weather.html
{% extends 'base.html' %}


{% block content %}


    <div class="main-w3layouts wrapper">
        <h1>Город, для которого вы хотите узнать погоду. </h1>
        <div class="main-agileinfo">
            <div class="agileits-top">
                <form action="{% url 'weather:weather-ui' %}" method="post">
                    {% csrf_token %}
                    <input class="text" type="text" name="city" placeholder="Город" required="">


                    <div class="wthree-text">

                        <div class="clear"></div>
                    </div>
                    <input type="submit" value="Узнать погоду">
                    <a href="{% url 'weather:logout' %}">Выход</a>
                </form>

            </div>
        </div>
        {% if type != 'weather-get' %}

            <div class="main-agileinfo">
                <div class="agileits-top">
                    <h1>Информация</h1>
                    {% if error_type %}
                        <table>
                            <tr>
                                <td>error_type</td>
                                <th>{{ error_type }}</th>

                            </tr>

                            <tr>
                                <td>error_info</td>
                                <th>{{ error_info }}</th>

                            </tr>
                        </table>
                    {% else %}
                        
                        <table class="table">
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Город</td>
      <td>{{ location_name }}</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Страна</td>
      <td>{{ location_country }}</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Регион</td>
      <td>{{ location_region }}</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td>Временная зона</td>
      <td>{{ location_timezone }}</td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td>Температура</td>
      <td>{{ location_temperature }}</td>
    </tr>
    <tr>
      <th scope="row">6</th>
      <td>{% for des in location_weather_descriptions %}
                                    {{ des }}
                                {% endfor %}</td>
      <td>{% for icon in location_weather_icons %}
                                    <img src="{{ icon }}">
                                {% endfor %}</td>
    </tr>
  </tbody>
</table>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    {% if not user.is_authenticated %}
        Уже авторизован
        <script type="text/javascript">

            window.location.replace('{% url 'weather:login' %}');
        </script>
    {% endif %}
{% endblock %}